### ISSUE TITLE
[DOC]: Should I be using Native Linux like Ubuntu 22 and not WSL2?

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1194]
### How would you describe the priority of this documentation request

Low (would be nice)

### Please provide a link or source to the relevant docs

theReadme

### Describe the problems in the documentation

It doesn't really state anywhere but I know with CUDA programming and the `nsys` command among some other things I noticed, not everything works on WSL2.  

I'm having problems with Docker and restarting using `systemctl` in WSL2 and was told maybe native Linux is better.  

Can you confirm?

### (Optional) Propose a correction

Clearly state separate instructions for Linux and WSL2 because there are some key differences right?  Where as people might assume Ubuntu 22 on WSL2 is Ubuntu 22.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by jarmak-nv** [comment]
Hey @nyck33 WSL2 isn't officially supported by Morpheus - while you may be able to run it, it's not something we've tested and it's definitely something that could cause problems. Unless you see WSL2 specified - I wouldn't assume it's an option (examples of when it is noted can be seen in the [RAPIDS install guide](https://docs.rapids.ai/install#wsl2), or the [CUDA Toolkit installer that has a specific WSL option.](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0))

I'm going to close this as will not complete, but if Morpheus on WSL2 is something you do want to see - feel free to file a feature req rather than a doc req and we can use it in our future release planning work.

Please re-open, file a followup issue, or start a discussion (for more free-form talking), if you have any concerns here.
