### ISSUE TITLE
[DOC]: how do you pre-parse apache logs?  With regex or NLP?

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1249]
### How would you describe the priority of this documentation request

Medium

### Describe the future/missing documentation

...'BERT language model using a toy dataset of just 1000 previously parsed apache server logs as a labeled data' it says here: https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/models/training-tuning-scripts/log-parsing-models/log-parsing-training.ipynb so I googled parsing apache logs and see things like: https://www.loggly.com/ultimate-guide/parsing-apache-logs/ but that seems low-tech and maybe not in line with all the NLP being used in Morpheus so can you tell me how you did it, and if you didn't use NLP, suggest some NLP ways to do this?

### Where have you looked?

See above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by jarmak-nv** [comment]
Hey @nyck33 

We used an open dataset of apache logs and a traditional regex parser, https://github.com/amandasaurus/apache-log-parser, to create an example training dataset. 

Any specific bugs/features/documentation issues with Morpheus, please open an issue to resolve, otherwise for more free-form responses please open a discussion on GitHub. Thanks!
