### ISSUE TITLE
[BUG] Calling set_meta with a list of strings raises an exception on a second call

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#286]
**Describe the bug**
Calling `set_meta` where values is a `list` or `cudf.Series` of string values raises an exception on a second call. The first call which creates the new column succeeds while the second call, updating values over a set of sliced rows raises an exception.

Issue seems to be centered around the fact that cupy doesn't support arrays of strings, while cudf does. This bug occurs in both C++ & Python execution modes.

Once this is fixed we need to remove the work-around in `examples/abp_pcap_detection/abp_pcap_preprocessing.py` on line 176.

Causes #282

**Steps/Code to reproduce bug**
```python
import os
import string

from morpheus._lib.file_types import FileTypes
from morpheus.io.deserializers import read_file_to_df
from morpheus.messages.multi_message import MultiMessage
from morpheus.messages.message_meta import MessageMeta

input_file = os.path.join(os.getenv('MORPHEUS_ROOT', '.'), 'tests/tests_data/filter_probs.csv')

df = read_file_to_df(input_file, file_type=FileTypes.Auto, df_type='cudf')
meta = MessageMeta(df)
mm1 = MultiMessage(meta, 0, 5)
mm2 = MultiMessage(meta, 5, 5)

values = list(string.ascii_letters)

mm1.set_meta('letters', values[0:5])
mm2.set_meta('letters', values[5:10])
```

**Comment by cwharris** [comment]
Bug caused by lack of string for `iloc` assignments on existing string columns (https://github.com/rapidsai/cudf/issues/11298), and our use of it in `set_meta`. https://github.com/nv-morpheus/Morpheus/blob/c3a3ddf6f1421175345ca08aaae933658c79757e/morpheus/messages/multi_message.py#L147-L152

Possible workaround by updating `set_meta` to detect string assignments, create a null-filled column, and use `iloc` instead of loc, such as:
```python
df['letters'].iloc[0:5]  = values[0:5]
df['letters'].iloc[5:10] = values[5:10]
```
