### ISSUE TITLE
Investigate cuDF 22.10 JSON Deserializer

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#397]
In 22.10, cuDF is releasing a new JSON deserializer which should be GPU accelerated. The tracking milestone is located here:

https://github.com/rapidsai/cudf/milestone/13

We should test the alpha releases to answer the following questions:

1. What differences will there be between the pandas JSON deserializer and the cuDF JSON deserializer?
   2. Currently, we treat the JSON and CSV deserializers interchangeably. If we change the default to the cuDF deserializer, what API changes would be needed?
3. Are there any bugs when trying to deserialize our test data?
   4. We should run all of the test and validation data through the alpha builds to file any bugs for issues that come up. This way they can be resolved before the release (and provide feedback to the cuDF team).

**Comment by cwharris** [comment]
Working off of these branches to check cudf 22.10 compatibility:

https://github.com/cwharris/srf/tree/cudf-22.10-integration
https://github.com/cwharris/morpheus/tree/cudf-22.10-integration

Some extra deps will need to be installed in the morpheus conda environment for SRF to build properly. this includes ucx, nlohmann_json, and libhwloc. check SRF dev env yaml for versions.

`-DCPM_srf_SOURCE` will need to be changed in Morpheus to point to _your_ srf dir instead of my local one. Figure this is an easy enough change that I'm not going to spend time figuring out how to avoid it. Wont make it in to the final PR anyway. Though it might be nice for dev purposes...

**Comment by cwharris** [comment]
> We should run all of the test and validation data through the alpha builds

Where is this data and which pipelines do we need to run? I'm searching for it but I'm unsure.

**Comment by dagardner-nv** [comment]
I tested out 22.12 in another issue (#550). In Morpheus we don't set the `engine` argument, leaving us with the default of `engine='auto'`, however we do set `lines=True`. The result is that in both versions this combination results in using the cudf engine. 

In 22.12 using cudf_experimental resulted in slightly slower reads  than the cudf engine in 22.08 or 22.12. Reading a large JSON file (161MB `examples/data/abp_pcap_dump.jsonlines`) took about ~0.05s slower :
|Engine + Ver | Time (sec) |
| ---- | ----------- |
| cudf 22.08 | 0.1228 |
| cudf 22.12 | 0.1223 |
| cudf_experimental 22.12 | 0.1736 |

**Comment by karthikeyann** [comment]
23.02 cudf has JSON writer 
https://github.com/rapidsai/cudf/blob/branch-23.02/cpp/include/cudf/io/json.hpp#L829

**Comment by dagardner-nv** [comment]
Closing this issue as we are now in cudf 23.02
Using the new json writer is tracked in issue #761 and PR #888
