### ISSUE TITLE
[BUG] Relative paths in the CLI should always be computed as relative to the root

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#60]
**Describe the bug**
Some of the default values for command line flags are relative paths ex:
```
@click.option('--labels_file', default="data/labels_nlp.txt",
```

The problem then is that this only works when run from the root of the repo.  Several of our own examples are run from within the example sub-directory.

**Comment by mdemoret-nv** [comment]
After speaking with @dagardner-nv, there are 4 scenarios that require the data files that we need to support with the CLI:

1. Using the CLI from `MORPHEUS_ROOT` with a developer install of morpheus `pip install -e .`
2. Using the CLI from `MORPHEUS_ROOT` with a full install of morpheus `pip install .`
3. Using the CLI from the examples folder with a developer install of morpheus `pip install -e .`
4. Using the CLI from the examples folder with a full install of morpheus `pip install .`

This will likely require bringing the `data` directory into the python package via `setup.py` so that it can be discovered via `morpheus.__file__`
