### ISSUE TITLE
[BUG]: Upgrade `protobuf` to version 4.xx.xx

### ISSUE THREAD

**Issue by tanmoyio** [nv-morpheus/Morpheus#601]
### Version

22.08

### Describe the bug.

Morpheus supports protobuf < 3.20
But cudf requires version > 4.xx (as its using the `builder.py`)
there is a workaround if we copy the `builder.py` from protobuf==4.xx and paste it into protobuf<3.20

But for sake of convenience it would be great if Morpheus comes with latest protobuf support

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment]
The `cudf` library doesnt support `protobuf=4.20.*` until version `23.02`. Currently Morpheus is using `cudf=22.10`. Upgrading to `protobuf=4.*` has a few issues that we would need to figure out first:

1. Upgrading to `cudf>22.12` would require us to use `protobuf=4.*` but there are a few issues preventing this
   1. Upgrading to `cudf>22.12` adds dependencies on both `cuda-toolkit` and `cudatoolkit` which we would like to avoid.
   1. This adds multiple GB to our docker containers and complicates the CMake build
   1. This is caused by requirements on the `cuda-python` package
   1. Ideally, this would be sorted out before we upgrade to `cudf>22.12` (Which is being tracked [here](https://github.com/orgs/rapidsai/projects/81/))
1. In general, we try to follow the versions outlined in the conda-forge pinning feedstock located [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml)
   1. This increases our compatibility with packages available on `conda-forge`
   1. Currently, the supported version of `libprotobuf` is 3.21, shown [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L503)
   1. So I am hesitant to upgrade the `libprotobuf` version since it could cause issues with the conda solver

Once the cudf upgrade to CUDA 12 is complete, we will revisit upgrading the cuDF version and protobuf versions.
